from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / '256_calculadora.png'

# Sizing
BIG_FONT_SIZE = 60
MEDIUM_FONT_SIZE = 20
SMALL_FONT_SIZE = 10
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500

#Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'